---
- hosts: all
  become_user: root
  become: true
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
    - name: Install Docker module for Python
      pip:
        name: docker
    - name: Pull the Jenkins Docker image
      docker_image:
        name: "samgabrail/jenkins-tf-vault-ansible:latest"
        source: pull
        state: present
        force_source: yes
    - name: Create Jenkins container
      docker_container:
        name: "jenkins"
        image: "samgabrail/jenkins-tf-vault-ansible:latest"
        state: started
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home
