---
- hosts: webblog
  become_user: root
  become: true
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
    - name: Install unzip
      package:
        name: unzip
        update_cache: yes
    - name: Download and install consul binary
      unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /usr/local/bin/
        remote_src: True
    - name: Download and install consul binary
      unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /usr/local/bin/
        remote_src: True
    - name: Create consul config directory
      file: state=directory path=/etc/consul.d
    - name: Copy consul config to server
      copy: src=consul_config.hcl dest=/etc/consul.d
    - name: Copy consul service to server
      copy: src=consul.service dest=/etc/systemd/system/consul.service
    - name: Start consul service
      systemd:
        state: started
        name: consul
        daemon_reload: yes

- hosts: webblog-db-vm
  become_user: root
  become: true
  tasks:
    - name: Install Docker module for Python
      pip:
        name: docker
    - name: Pull the Mongo Docker image
      docker_image:
        name: "mongo:4.2.7"
        source: pull
        state: present
        force_source: yes
    - name: Create Mongo container
      docker_container:
        name: "mongo"
        image: "mongo:4.2.7"
        state: started
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: "{{ mongo_root_user }}"
          MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_root_password }}"
        volumes:
          - mongo_data:/data/db
    - name: Copy Mongo service to server
      copy: src=mongo_service.json dest=/etc/consul.d
    - name: Restart consul service
      systemd:
        state: started
        name: consul
        daemon_reload: yes

- hosts: webblog-app-vm
  become_user: root
  become: true
  tasks:
    - name: Download and install vault binary
      unarchive:
        src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
        dest: /usr/local/bin/
        remote_src: True
    - name: Create vault config directory
      file: state=directory path=/etc/opt/vault/
    - name: Copy vault config to server
      copy: src=vault_agent_config.hcl dest=/etc/opt/vault/
    - name: Copy role_id for Vault Agent
      copy: src=/tmp/app_role_id dest=/tmp/webblog_role_id
    - name: Copy wrapped_secret_id for Vault Agent
      copy: src=/tmp/app_wrap_secret_id dest=/tmp/webblog_wrapped_secret_id
    - name: Copy vault service to server
      copy: src=vault.service dest=/etc/systemd/system/vault.service
    - name: Start vault service
      systemd:
        state: started
        name: vault
        daemon_reload: yes
    - pause:
        seconds: 15
    - name: Copy Webblog App
      copy: src=../../Application/app dest=/home/adminuser/
    - name: Install Webblog Python Dependencies
      pip:
        requirements: /home/adminuser/app/requirements.txt
    - name: Copy Webblog App service to server
      copy: src=webblog.service dest=/etc/systemd/system/webblog.service
    - name: Start Webblog App service
      systemd:
        state: started
        name: webblog
        daemon_reload: yes
    - name: Copy Webblog App service to server
      copy: src=webblog_app_service.json dest=/etc/consul.d
    - name: Restart consul service
      systemd:
        state: started
        name: consul
        daemon_reload: yes
