---
- hosts: all
  become_user: root
  become: true
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
    - name: Install Docker module for Python
      pip:
        name: docker
    - name: Pull the Jenkins Docker image
      docker_image:
        name: "samgabrail/jenkins-tf-vault-ansible:latest"
        source: pull
        state: present
        force_source: yes
    - name: Change file ownership, group and permissions
      file:
        path: /home/adminuser/jenkins_data
        state: directory
        recurse: yes
        owner: adminuser
        group: adminuser
    - name: Create Jenkins container
      docker_container:
        name: "jenkins"
        image: "samgabrail/jenkins-tf-vault-ansible:latest"
        state: started
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /home/adminuser/jenkins_data:/var/jenkins_home
    - name: Create .ssh directory
      file: state=directory path=/home/adminuser/jenkins_data/.ssh
    - name: Copy the Private SSH Key for Jenkins to Access Azure VMs
      copy:
        src: /mnt/c/Users/Sam/.ssh/id_rsa
        dest: /home/adminuser/jenkins_data/.ssh/id_rsa
        owner: adminuser
        group: adminuser
        mode: 0400
    - name: Install unzip
      package:
        name: unzip
        update_cache: yes
    - name: Download and install consul binary
      unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /usr/local/bin/
        remote_src: True
    - name: Create consul config directory
      file: state=directory path=/etc/consul.d
    - name: Copy consul config to server
      copy: src=consul_config.hcl dest=/etc/consul.d
    - name: Copy consul service to server
      copy: src=consul.service dest=/etc/systemd/system/consul.service
    - name: Start consul service
      systemd:
        state: started
        name: consul
        daemon_reload: yes
    - name: Install Envoy Dependencies
      apt:
        update_cache: yes
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add an Apt signing key
      apt_key:
        url: https://getenvoy.io/gpg
        state: present
    - name: Add Envoy repository into sources list
      apt_repository:
        repo: deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb bionic stable
        state: present
    - name: Install Envoy
      apt:
        name: getenvoy-envoy
        update_cache: yes